input {
  file {
    path => "/usr/share/logstash/logs/*.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/.sincedb"
  }
}

filter {
  if [log][file][path] =~ "app.log" {

    dissect {
      mapping => {
        "message" => "%{timestamp} [%{correlation_id}] [%{loglevel}] %{logger}: %{log_message}"
      }
    }
    
    date {
      match => [ "timestamp", "yyyy-MM-dd HH:mm:ss,SSS" ]
      target => "@timestamp"
      remove_field => [ "timestamp" ]
    }
   
   if [log_message] =~ "Batch generation failed" {
      grok {
        match => {
          "log_message" => "Batch generation failed: %{INT:api_status_code}, message='%{DATA:api_error_message}', url='%{DATA:api_url}'"
        }
      }
      

      if [api_url] {
        mutate {
          gsub => [
            "api_url", "TrustedClientToken=[^&]+", "TrustedClientToken=REDACTED",
            "api_url", "Sec-MS-GEC=[^&]+", "Sec-MS-GEC=REDACTED"
          ]
        }
      }
      
      mutate {
        gsub => [
          "log_message", "TrustedClientToken=[^&']+", "TrustedClientToken=REDACTED",
          "log_message", "Sec-MS-GEC=[^&']+", "Sec-MS-GEC=REDACTED"
        ]
      }
    }
  }
}


output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}